### ISSUE TITLE
Wrong Source Code on CurseForge

### ISSUE THREAD

**Issue by TheBooz** [OnesAndZer0s/TrumpetSkeleton-TMod#3]
The Curseforge source code leads here...

...except the source code is a tModLoader mod, not a Java Forge mod.

Side note: Please fix spawn weights.

**Comment by OnesAndZer0s** [comment]
Okay, not going to lie, a bit of a blunder on my part. I made two mods about the trumpet skeleton and confused them. Fixing them now, thank you

**Comment by OnesAndZer0s** [comment]
Here you go: https://github.com/OnesAndZer0s/TrumpetSkeleton-MC
I'll work on the spawn weights rn. I am going to be honest, I completely forgot about this project
